export let DATA = [
    {
      id:1,
      imgtitle: 'Arshdeep',
      src: require('../../../images/team_arsh.png'),
      alt:'Arsh',
      name:'Arshdeep Singh',
      title:'Full stack web developer / Project Manager',
      ahref:"https://www.linkedin.com/in/arsh-uppal/",
      gahref:"https://github.com/arsh-uppal",
    },
    {
        id:2,
        imgtitle: 'Eduardo',
        src: require('../../../images/team_edu.png'),
        alt:'Edu',
        name:'Eduardo Pereira do Carmo',
        title:'Lead Full stack web developer',
        ahref:"https://www.linkedin.com/in/eduardopcarmo/",
        gahref:"https://github.com/eduardopcarmo",
    },
    {
        id:3,
        imgtitle: 'Yalcin',
        src: require('../../../images/team_yalcin.png'),
        alt:'Yalcin',
        name:'Yalcin Tatar',
        title:'Full Stack Developer',
        ahref:"https://www.linkedin.com/in/yalcin-tatar/",
        gahref:"https://github.com/yalcinos",
    },
    {
        id:4,
        imgtitle: 'Saebom',
        src: require('../../../images/team_sb1.png'),
        alt:'Saebom',
        name:'Saebom Pak',
        title:'Front-end Developer',
        ahref:"https://www.linkedin.com/in/saebompak/",
        gahref:"https://github.com/saebomp",
    },
    {
        id:5,
        imgtitle: 'Saebyeol',
        src: require('../../../images/team_sb2.png'),
        alt:'Saebyeol',
        name:'Saebyeol Pak',
        title:'Front-end Developer',
        ahref:"https://www.linkedin.com/in/saebyeolpak/",
        gahref:"https://github.com/saebyeolp",
    },
    {
        id:6,
        imgtitle: 'Harry',
        src: require('../../../images/team_harry.png'),
        alt:'Harry Tran',
        name:'Harry Tran',
        title:'Lead UX/UI Designer',
        ahref:"https://www.linkedin.com/in/harryvtran/",
        gahref:"",
    },
    {
        id:7,
        imgtitle: 'Ramandeep',
        src: require('../../../images/team_raman.png'),
        alt:'Ramandeep Kaur',
        name:'Ramandeep Kaur',
        title:'UX/UI Designer',
        ahref:"https://www.linkedin.com/in/ramandeep/",
        gahref:"",
    },
    
  ]