[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
  from = "http://www.kovanapp.com/*"
  to = "https://www.kovanapp.com/:splat"
  status = 301
  force = true

  
[[redirects]]
  from = "http://kovanapp.com/*"
  to = "https://kovanapp.com/:splat"
  status = 301
  force = true